### ISSUE TITLE
Mods already containing CustomTextures/Meshes folders incorrectly assigned those mod types

### ISSUE THREAD

**Issue by maxkagamine** [Nexus-Mods/game-valheim#4]
Example mod structures:

```
config
└── SomePlugin.cfg
plugins
├── CustomTextures
│   └── texture_foo_MainTex.png
└── SomePlugin.dll
```

**Expected:** BepInEx Root Mod
**Actual:** CustomTextures Mod (due to presence of a `texture_*.png` and lower priority number)

```
CustomMeshes
└── foo
    └── default.obj
CustomTextures
├── texture_foo_d_MainTex.png
└── texture_foo_n_BumpMap.png
```

**Expected:** _Default_
**Actual:** CustomMeshes Mod (due to presence of an `*.obj` file)

Could the test function for the CustomTextures & CustomMeshes mod types perhaps ignore textures/meshes whose path contains the "CustomTextures" or "CustomMeshes" directory, respectively?

https://github.com/Nexus-Mods/game-valheim/blob/27aba5079f84ecc5df397783faa7dac0213252ad/index.ts#L486-L507

To create those dummy mods for testing:

```
mkdir -p test\ root\ mod/{config,plugins/CustomTextures} test\ default\ mod/Custom{Meshes/foo,Textures} && touch test\ root\ mod/config/SomePlugin.cfg test\ root\ mod/plugins/CustomTextures/texture_foo_MainTex.png test\ root\ mod/plugins/SomePlugin.dll test\ default\ mod/CustomMeshes/foo/default.obj test\ default\ mod/CustomTextures/texture_foo_{d_MainTex,n_BumpMap}.png
```

**Comment by IDCs** [comment]
@maxkagamine thanks for the extremely well documented bug report and apologies for dragging this on for so long.
