### ISSUE TITLE
Unable to update from Github repo

### ISSUE THREAD

**Issue by fressno** [Nexus-Mods/game-valheim#8]
Getting an error related to the title of this issue.
And the entire modding is broken cus of it.
![Screenshot 2023-09-03 192633](https://github.com/Nexus-Mods/game-valheim/assets/26026556/6ce3b4be-3293-4833-8f1f-30d9501e1732)
Getting this report in Nexus Vortex
And this error in the CMD prompt when its loading:
[Error  : Unity Log] MissingMethodException: string Utils.GetSaveDataPath()
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.UI.Image:OnCanvasHierarchyChanged()

the game itself is unplayable.
You cant build anything. and things break. you cant chop any trees, open any boxes, use the workbench. and the 3rd person camera is broken.
And much more.

**Comment by IDCs** [comment]
Fixed in the latest version of the Valheim extension
